<?php 
$this->title = 'Main';
$this->headTitle($this->title);
?>
<?php 
require_once 'library/Sunny/Scripts/site_dependent/database_connection.php';

?><center>

<form action="" method="post">
<table border = '0' align="center">
<tr><th colspan='7'>ToDo List (<a href='/index/new'>Add New</a>) </th></tr>
<tr id='tableHead'>
	<th>id</th>
	<th>name</th>
	<th>text</th>
	<th>time</th>
	<th>priority</th>
	<th>delete</th>
	<th>edit below</th>
</tr>
    <?php 
    $lineNr = 0;
    foreach ($this->resultGetTodoList as $todo){
        $todo = get_object_vars($todo);
        ?>
        
        <tr align="center" bgcolor='<?php echo (($lineNr % 2) ? '' : 'lavender') ?>' >
        	<td><?php echo $todo['id']?></td>
        	<td>bisu10</td>
        	<td><?php echo $todo['note']?></td>
        	<td><?php echo $todo['date']?></td>
        	<td><?php echo $todo['prio']?></td>
        	<td></td>
        	<td></td>
        </tr>
        <?php 
        $lineNr ++;
    }
    
    ?>

<!-- here is the ToDo entrys -->
<tr><td id='toDoNr' colspan='7'></td></tr>
</table>
</form>

<hr />

</center>